name: project_cantina_cd
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 
      - run: gh auth login -h 'assard'
      - run: gh release create v0.0.1.test 'target/*.jar'
