name : project_cantina
on : [push, pull_request]
jobs:
  compilation_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2 
    - run: sudo apt-get update && sudo apt-get install -y maven # Installation of maven
    - run: mvn clean
    - run: mvn verify

  publish:
    runs-on: ubuntu-18.04
    dependencies:
      - compilation_and_test
    only:
      -tags
    script:
      gh release create v0.0.1 'target/*.jar'