name : project_cantina_push_pull
on : [push, pull_request]
jobs:
  compilation_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2 
    - run: sudo apt-get update && sudo apt-get install -y maven # Installation of maven
    - run: mvn verify